-- CREATE TABLE Player (
--     ID INTEGER NOT NULL,
--     Name VARCHAR NOT NULL,
--     Nationality VARCHAR NOT NULL,
--     Birth_date TIMESTAMP,
--     Titles INTEGER,
--     PRIMARY KEY (ID)
-- );